name: Sample Book App Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-install-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - run: echo "Installing all necessary node dependencies.."
      - name: Install all dependencies
        run: npm install
      - run: echo "Dependecies successfully installed.." 
  deploy-dev:
    runs-on: self-hosted
    needs: build-install-deps
    steps:
      - uses: actions/checkout@v6
      - run: echo "Deployment to DEV environment has started.."
      - name: Install dependecies
        run: npm install
      - name: Cleanup of old running service
        shell: bash
        run: node_modules/.bin/pm2 delete \"books-dev\" || exit 0
      - name: Rnning service
        run: node_modules/.bin/pm2 start -n \"books-dev\" index.js -- 1010
      - run: echo "Deployment to DEV environment finished.."
  test-dev:
    runs-on: self-hosted
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on DEV environment.."
  deploy-stg:
    runs-on: self-hosted
    needs: test-dev
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to STG environment has started.."
  test-stg:
    runs-on: self-hosted
    needs: deploy-stg
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on STG environment.."
  deploy-prd:
    runs-on: self-hosted
    needs: test-stg
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to PRD environment has started.."
  test-prd:
    runs-on: self-hosted
    needs: deploy-prd 
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on PRD environment.."
    
